package com.example.chillstay.ui.navigation

object Routes {
    const val WELCOME = "welcome"
    const val CAROUSEL = "carousel"
    const val MAIN = "main"
    const val HOME = "home"
    const val AUTHENTICATION = "authentication"
    const val SIGN_IN = "sign_in"
    const val SIGN_UP = "sign_up"
    const val HOTEL_DETAIL = "hotel_detail"
    const val ROOM = "room"
    const val ROOM_GALLERY = "room_gallery"
    const val BOOKING = "booking"
    const val BOOKING_DETAIL = "booking_detail"
    const val VIP_STATUS = "vip_status"
    const val SEARCH = "search"
    const val BOOKMARK = "bookmark"
    const val MY_TRIPS = "my_trips"
    const val PROFILE = "profile"
    const val VOUCHER = "voucher"
    const val VOUCHER_DETAIL = "voucher_detail"
    const val REVIEW = "review"
    const val BILL = "bill"
    const val MY_REVIEWS = "my_reviews"
    const val ALL_REVIEWS = "all_reviews"
    const val ADMIN_HOME = "admin_home"
    const val ADMIN_ACCOMMODATION = "admin_accommodation"
    const val ADMIN_ACCOMMODATION_EDIT = "admin_accommodation_edit"
    const val ADMIN_ROOM_MANAGE = "admin_room_manage"
    const val ADMIN_ROOM_EDIT = "admin_room_edit"
}
